# Generated by Django 4.2.10 on 2024-04-05 19:36

from django.db import migrations, models
import store.models.product


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_user_delete_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.FilePathField(path=store.models.product.images_path),
        ),
    ]
